version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    restart: always
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: Oracle123
      ORACLE_DATABASE: XEPDB1
      APP_USER: appuser
      APP_USER_PASSWORD: apppass
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
